### PR TITLE
Updated BPASS setup and instructions

### PR DESCRIPTION
**Pull request by eor**
I tried to  fix the BPASS setup instructions and managed to download, extract, and convert the stellar atmosphere files to ascii but had no time to finish the task.

What remains to be done:

- [x] compile the ascii files with cloudy and test them
- [x] figure out which file we should be using (chabrier 300 or imf135_100?). In the input template file for cloudy we are using the latter, but the documentation refers to the former.
- [x] update the documentation
- [x] possibly: add a test for this to the test suite (see also #79 )

### CODE REVIEW

**Review by raulorteg — APPROVED** [review]
I think evertyhing looks good. Maybe a note to ourselfs is that we should probably pin down the specific versions of the packages that we use in the requirements, like:
```
...
gdown==4.5.3
....
```
So that we dont run into problems in the future, and it would also help if we dockerize the project

**Comment by eor** [comment]
A couple of changes:

- automated setup of the BPASS model
- a test to verify the BPASS binary file exists
- updated BPASS and testing documentation
- I updated the wait time for the QueueManager test to 60 seconds as 30 seconds were not enough on my system
- doc strings and comments here and there

**Comment by eor** [comment]
I changed the stellar atmosphere model in the template .in file `cloudy_input_template.in` but I am not sure what the file is actually used for. If it is no longer needed, can it be removed? 

Equally, is the binary file `bpass_v2p2.1_imf_chab300_burst_binary.mod` usable across different installations or should it be compiled anew? If so, it might make more sense to supply the ascii file instead.

**Review by raulorteg — COMMENTED** [review]
I think it looks good. However should the conda requirements be written in a .txt file as for pip? I think it is easier for conda to export the environment to a yml file with  ```conda env export > environment.yml``` so that users can create the environment easily as ```conda env create -f environment.yml```. Otherwise ```requirements.txt```and ```requirements_conda.txt```are the same and so one is redundant.

**Comment by eor** [comment]
> ...  should the conda requirements be written in a .txt file as for pip? ... Otherwise `requirements.txt`and `requirements_conda.txt`are the same and so one is redundant.

You are right that they are a bit redundant here as they contain the same information. I kept them separate because sometimes the package names can differ between pip and conda, e.g. for torch / pytorch 

> I think it is easier for conda to export the environment to a yml file with `conda env export > environment.yml` so that users can create the environment easily as `conda env create -f environment.yml`. 

That seems like a sensible idea but also assumes a user wants to create a new environment rather than keep using an existing one. Not sure what a potential user might prefer

Maybe we can make this a separate issue and discuss it during our next meeting?

**Pull request merged**
